fix(sec): upgrade org.apache.commons:commons-dbcp2 to 2.9.0
spring-cloud/spring-cloud-sleuth pull request #2216
Opened 2022-10-13 00:45 UTC by sd8089730

### What happened？
There are 1 security vulnerabilities found in org.apache.commons:commons-dbcp2 2.8.0
- [MPS-2022-12024](https://www.oscs1024.com/hd/MPS-2022-12024)

### What did I do？
Upgrade org.apache.commons:commons-dbcp2 from 2.8.0 to 2.9.0 for vulnerability fix

### What did you expect to happen？
Ideally, no insecure libs should be used.

### The specification of the pull request
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

2022-10-13 00:45 UTC, pivotal-cla commented
@sd8089730 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-sleuth&pullRequestId=2216)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-sleuth&pullRequestId=2216) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2022-10-13 00:47 UTC, pivotal-cla commented
@sd8089730 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-sleuth&pullRequestId=2216)!

2022-10-13 03:43 UTC, jonatan-ivanov commented
Could you please provide a link to this that all of the maintainers can understand (english is fine)?

2022-10-13 03:44 UTC, jonatan-ivanov requested changes

2022-10-13 03:44 UTC, jonatan-ivanov commented on pom.xml
> -<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
Please do not reformat this.

2022-10-13 03:44 UTC, jonatan-ivanov commented on pom.xml
> +</project>
Please do not reformat this.

2022-10-13 03:44 UTC, jonatan-ivanov commented on pom.xml
> +		<commons-dbcp2.version>2.9.0</commons-dbcp2.version>
Is there a patch version (2.8.x) of dbcp where this issue is fixed?

2022-12-01 10:50 UTC, marcingrzejszczak commented
Ping @sd8089730

2023-01-16 15:34 UTC, closed without merging